### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by asm0dey** [PPACI/wrk2img#1]
With such input:

```
Running 1m test @ http://127.0.0.1:8080/sys/ping
  2 threads and 100 connections
  Thread calibration: mean lat.: 1.473ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 1.496ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.46ms    2.24ms  44.06ms   98.51%
    Req/Sec     1.05k   265.56     5.40k    89.45%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.18ms
 75.000%    1.54ms
 90.000%    1.93ms
 99.000%   11.72ms
 99.900%   30.74ms
 99.990%   39.52ms
 99.999%   44.03ms
100.000%   44.10ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.111     0.000000            1         1.00
       0.642     0.100000         9985         1.11
       0.808     0.200000        19969         1.25
       0.940     0.300000        29880         1.43
       1.060     0.400000        39813         1.67
       1.183     0.500000        49762         2.00
       1.246     0.550000        54786         2.22
       1.312     0.600000        59701         2.50
       1.383     0.650000        64679         2.86
       1.462     0.700000        69689         3.33
       1.545     0.750000        74666         4.00
       1.591     0.775000        77137         4.44
       1.644     0.800000        79634         5.00
       1.703     0.825000        82120         5.71
       1.768     0.850000        84596         6.67
       1.844     0.875000        87067         8.00
       1.887     0.887500        88318         8.89
       1.935     0.900000        89574        10.00
       1.985     0.912500        90819        11.43
       2.046     0.925000        92039        13.33
       2.121     0.937500        93292        16.00
       2.167     0.943750        93911        17.78
       2.215     0.950000        94528        20.00
       2.265     0.956250        95149        22.86
       2.321     0.962500        95782        26.67
       2.381     0.968750        96409        32.00
       2.417     0.971875        96702        35.56
       2.459     0.975000        97020        40.00
       2.517     0.978125        97331        45.71
       2.609     0.981250        97637        53.33
       3.083     0.984375        97946        64.00
       4.923     0.985938        98101        71.11
       7.239     0.987500        98258        80.00
      10.287     0.989062        98412        91.43
      12.351     0.990625        98568       106.67
      15.359     0.992188        98723       128.00
      16.735     0.992969        98802       142.22
      18.175     0.993750        98879       160.00
      19.839     0.994531        98956       182.86
      21.983     0.995313        99034       213.33
      23.423     0.996094        99112       256.00
      24.255     0.996484        99152       284.44
      25.791     0.996875        99190       320.00
      26.479     0.997266        99228       365.71
      27.055     0.997656        99268       426.67
      27.727     0.998047        99306       512.00
      28.127     0.998242        99326       568.89
      28.639     0.998437        99345       640.00
      29.295     0.998633        99366       731.43
      30.047     0.998828        99384       853.33
      30.751     0.999023        99403      1024.00
      31.119     0.999121        99415      1137.78
      31.263     0.999219        99423      1280.00
      31.695     0.999316        99432      1462.86
      32.127     0.999414        99443      1706.67
      32.927     0.999512        99452      2048.00
      33.279     0.999561        99457      2275.56
      33.695     0.999609        99462      2560.00
      34.079     0.999658        99466      2925.71
      34.495     0.999707        99471      3413.33
      34.783     0.999756        99476      4096.00
      35.551     0.999780        99479      4551.11
      36.383     0.999805        99481      5120.00
      38.399     0.999829        99483      5851.43
      38.943     0.999854        99486      6826.67
      39.263     0.999878        99488      8192.00
      39.519     0.999890        99490      9102.22
      39.583     0.999902        99491     10240.00
      42.591     0.999915        99492     11702.86
      42.783     0.999927        99494     13653.33
      42.783     0.999939        99494     16384.00
      42.847     0.999945        99496     18204.44
      42.847     0.999951        99496     20480.00
      42.847     0.999957        99496     23405.71
      43.583     0.999963        99497     27306.67
      43.583     0.999969        99497     32768.00
      43.871     0.999973        99498     36408.89
      43.871     0.999976        99498     40960.00
      43.871     0.999979        99498     46811.43
      44.031     0.999982        99499     54613.33
      44.031     0.999985        99499     65536.00
      44.031     0.999986        99499     72817.78
      44.031     0.999988        99499     81920.00
      44.031     0.999989        99499     93622.86
      44.095     0.999991        99500    109226.67
      44.095     1.000000        99500          inf
#[Mean    =        1.458, StdDeviation   =        2.240]
#[Max     =       44.064, Total count    =        99500]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  119802 requests in 1.00m, 22.05MB read
Requests/sec:   1996.65
Transfer/sec:    376.32KB
```

I see following error:

```
Traceback (most recent call last):
  File "/usr/sbin/wrk2img", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.7/site-packages/wrk2img/main.py", line 29, in cli
    data, website = parser.parse_stdin()
  File "/usr/lib/python3.7/site-packages/wrk2img/parser.py", line 27, in parse_stdin
    parsed_wrk_output = self.parse_wrk_output(wrk_ouput)
  File "/usr/lib/python3.7/site-packages/wrk2img/parser.py", line 60, in parse_wrk_output
    website = websites[0]
IndexError: list index out of range
```

**Comment by PPACI** [comment]
Hi thank you for opening this issue.
I’ll check to write a fix.

**Comment by asm0dey** [comment]
Thank you!

вт, 18 дек. 2018 г., 9:19 Pierre PACI notifications@github.com:

> Hi thank you for opening this issue.
> I’ll check to write a fix.
>

**Comment by PPACI** [comment]
It should be fixed with PR #2 
Can you try ?

**Comment by asm0dey** [comment]
Did you upload this to PyPI?

**Comment by PPACI** [comment]
Nope, will do today

**Comment by asm0dey** [comment]
Please, do it. I'm not python user, it's difficult for me to install not
from pip.
[image: photo]
Paul FInkelshteyn
Team lead at  Lamoda LLC
M  +7(915)208-2133  <+7(915)208-2133>
E  pavel.finkelshtein@gmail.com  <pavel.finkelshtein@gmail.com>
W  asm0dey.ru  <http://asm0dey.ru>
Skype pavel.finkelshtein <#SignatureSanitizer_SafeHtmlFilter_>
<http://facebook.com/asm0dey> <http://linkedin.com/in/asm0dey>
<http://twitter.vom/asm0di0> <http://vk.com/asm0dey>
<http://it.asm0dey.ru/podcast/feed/>


вт, 18 дек. 2018 г. в 14:39, Pierre PACI <notifications@github.com>:

**Comment by PPACI** [comment]
pip is now up to date with 1.0.1

**Comment by asm0dey** [comment]
I have following error:

```
Collecting wrk2img
  Using cached https://files.pythonhosted.org/packages/02/e7/6b6f1c02368ed39281ef6acd8aee6d7b7b6d821152f2a149353f0799c5fc/wrk2img-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-59u4civx/wrk2img/setup.py", line 3, in <module>
        with open('Readme.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'Readme.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-59u4civx/wrk2img/
```

**Comment by PPACI** [comment]
WTF.
I'll check and send you an update.

**Comment by PPACI** [comment]
My Build tool was broken. It's fixed. 1.0.3 is released on pypi fixing this problem
